name: Deploy to AppEngine

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: Auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build application
        run: npm install && npm run build

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}

      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
